# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: 'python:3.7'
definitions:
    steps:
        - step: &Linux-Lint
            name: Linux-Lint
            caches:
                - pip
            script:
                - pip install pdm
                - pdm install
                - ./lint.sh
        - step: &Linux-Test
            name: Linux-Test
            caches:
                - pip
            script:
                - pip install pdm
                - pdm install
                - pdm run pytest tests

pipelines:
    branches:
        master:
            - step: *Linux-Lint
            - step: *Linux-Test
    pull-requests:
        '**':
            - step: *Linux-Lint
            - step: *Linux-Test
    tags:
        '*':
            - step: *Linux-Lint
            - step: *Linux-Test
